<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/




    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/oauth2/token');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
    curl_setopt($ch, CURLOPT_USERPWD, 'ASnTwn2tO5vojqMccLPBCcE41aNplU7bG0Iw8iBmstXtXX2RA-SmxjW_jAQWLm06BT2HkvkOgnU6-fu9' . ':' . 'EJv270fVl2JzO46JIKNnCgBRRPn-xzkxoNrqIjG7w-uUUI0kPaNV2aY72dL5Rb2eDCRMsmwXRV4dXK_3');
    
    $headers = array();
    $headers[] = 'Accept: application/json';
    $headers[] = 'Accept-Language: en_US';
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
    $result = curl_exec($ch);
    $err=curl_error($ch);
    curl_close($ch);
    
    
    if($err){
    
        echo ' error: '.$err;
    
    }
    else{
    
        $response=json_decode($result);
    
       $response=json_decode($result,true);
    
       // return $response['access_token'];
       $access_token=$response->access_token;

       if($access_token){


        header('location: cancelsub.php?access_token='.$access_token);
       }


    
    }
    








?>