<?php


//include('C:\xampp\htdocs\Overflow\access_token.php');

function getAuthToken(){

    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/oauth2/token');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
    curl_setopt($ch, CURLOPT_USERPWD, 'ASnTwn2tO5vojqMccLPBCcE41aNplU7bG0Iw8iBmstXtXX2RA-SmxjW_jAQWLm06BT2HkvkOgnU6-fu9' . ':' . 'EJv270fVl2JzO46JIKNnCgBRRPn-xzkxoNrqIjG7w-uUUI0kPaNV2aY72dL5Rb2eDCRMsmwXRV4dXK_3');
    
    $headers = array();
    $headers[] = 'Accept: application/json';
    $headers[] = 'Accept-Language: en_US';
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
    $result = curl_exec($ch);
    $err=curl_error($ch);
    curl_close($ch);
    
    
    if($err){
    
        echo ' error: '.$err;
    
    }
    else{
    
        $response=json_decode($result);
    
       $response=json_decode($result,true);
    
        return $response['access_token'];
    
    }
    

}

oldcreateproduct(getAuthToken());
function oldcreateproduct(){

$token=getAuthToken();
$length = 32;    
$unique_id=substr(str_shuffle('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'),1,$length);

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/catalogs/products');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"name\": \"Overflow\",\n  \"description\": \"Note taking app\",\n  \"type\": \"SERVICE\",\n  \"category\": \"SOFTWARE\",\n  \"image_url\": \"https://i.ibb.co/Qc0b1Jt/cscsd-removebg-preview.png\",\n  \"home_url\": \"https://example.com/home\"\n}");

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer '.rawurldecode($token);
$headers[] = 'Paypal-Request-Id: '.rawurldecode($unique_id);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$err=curl_error($ch);
curl_close($ch);

if($err){

    echo ' error: '.$err;

}
else{

    $response=json_decode($result);
    //var_dump($response);
    $productID=$response->id;
    //var_dump($planID);

    if($productID){

        header('Location: createplan.php?productID='.$productID.'&access_token='.$token);
    }


}


}

//echo createaproduct(getAuthToken());


//$token = getAuthToken();
function createaproduct($token){

$length = 32;    
$unique_id=substr(str_shuffle('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'),1,$length);

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/catalogs/products');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"name\": \"Overflow\",\n  \"description\": \"Note taking app\",\n  \"type\": \"SERVICE\",\n  \"category\": \"SOFTWARE\",\n  \"image_url\": \"https://i.ibb.co/Qc0b1Jt/cscsd-removebg-preview.png\",\n  \"home_url\": \"https://example.com/home\"\n}");

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer '.rawurldecode($token);
$headers[] = 'Paypal-Request-Id: '.rawurldecode($unique_id);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$err=curl_error($ch);
curl_close($ch);

if($err){

    echo ' error: '.$err;

}
else{


    
    $response=json_decode($result,true);
 
     return $response['id'];



}






}



function createplan($token){

    $name="Premium";
    $description="Premium Plan";
    $img="https://i.ibb.co/Qc0b1Jt/cscsd-removebg-preview.png";
    $url="localhost/Overflow/views/index";
    
    
    
    
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();
    
    curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/billing/plans');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n    \"name\": \"$name\",\n    \"description\": \"$description\",\n    \"product_id\": \"$productID\",\n    \"billing_cycles\": [\n        {\n            \"frequency\": {\n                \"interval_unit\": \"MONTH\",\n                \"interval_count\": 1\n            },\n            \"tenure_type\": \"REGULAR\",\n            \"sequence\": 1,\n            \"total_cycles\": 0,   \n            \"pricing_scheme\": {\n                \"fixed_price\": {\n                    \"value\": \"20\",\n                    \"currency_code\": \"USD\"\n                }\n            }\n        }\n    ],\n    \"payment_preferences\": {\n        \"auto_bill_outstanding\": true,\n        \"payment_failure_threshold\": 1\n    }\n }");
    
    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Authorization: Bearer '.rawurldecode($token);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
    $result = curl_exec($ch);
    $err=curl_error($ch);
    curl_close($ch);
    
    if($err){
    
        echo ' error: '.$err;
    
    }
    else{
    
        $response=json_decode($result,true);
 //getproductid
        return $response['id'];

    }
}

?>