<?php 


function getAuthToken(){

    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/oauth2/token');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
    curl_setopt($ch, CURLOPT_USERPWD, 'ASnTwn2tO5vojqMccLPBCcE41aNplU7bG0Iw8iBmstXtXX2RA-SmxjW_jAQWLm06BT2HkvkOgnU6-fu9' . ':' . 'EJv270fVl2JzO46JIKNnCgBRRPn-xzkxoNrqIjG7w-uUUI0kPaNV2aY72dL5Rb2eDCRMsmwXRV4dXK_3');
    
    $headers = array();
    $headers[] = 'Accept: application/json';
    $headers[] = 'Accept-Language: en_US';
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
    $result = curl_exec($ch);
    $err=curl_error($ch);
    curl_close($ch);
    
    
    if($err){
    
        echo ' error: '.$err;
    
    }
    else{
    
        $response=json_decode($result);
    
       $response=json_decode($result,true);
    
        return $response['access_token'];
    
    }
    

}

echo getAuthToken();



//return productid
function createproduct($accesstoken,$name,$description,$img,$home_url,$uniqueid){


    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/catalogs/products');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"name\": \"$name\",\n  \"description\": \"$description\",\n  \"type\": \"SERVICE\",\n  \"category\": \"SOFTWARE\",\n  \"image_url\": \"$img\",\n  \"home_url\": \"$home_url\"\n}");
    
    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Authorization: Bearer '.$accesstoken;
    $headers[] = 'Paypal-Request-Id: '.$uniqueid;
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
    $result = curl_exec($ch);
    $err=curl_error($ch);
    curl_close($ch);
    
    if($err){
    
        echo ' error: '.$err;
    
    }
    else{
    
        $response=json_decode($result,true);
     
         return $response['id'];
    }

}



//echo listproducts(getAuthToken());
function listproducts($accesstoken){


    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/catalogs/products?page_size=2&page=1&total_required=true');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Authorization: Bearer '.$accesstoken;
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$err=curl_error($ch);
curl_close($ch);

if($err){

    echo ' error: '.$err;

}
else{

    var_dump($response=json_decode($result,true));
 
  //   return $response['id'];
}




}


//echo updateproduct('PROD-36Y141679S545991A',getAuthToken(),'replace','name','overflow');
function updateproduct($productid,$accesstoken, $operation,$path,$value){



    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/catalogs/products/'.$productid.'');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PATCH');

curl_setopt($ch, CURLOPT_POSTFIELDS, "[\n  {\n    \"op\": \"$operation\",\n    \"path\": \"/$path\",\n    \"value\": \"$value\"\n  }\n]");

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer '.$accesstoken;
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$err=curl_error($ch);
curl_close($ch);

if($err){

    echo ' error: '.$err;

}
else{

    var_dump($response=json_decode($result,true));
 
  //   return $response['id'];
}


}






//productdetails(getAuthToken());
function productdetails($accesstoken){



    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/catalogs/products/PROD-36Y141679S545991A');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer '.$accesstoken;
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

var_dump($response=json_decode($result,true));




}



















?>